"""The catch-up notes a migration leaves behind, and the one thing they have to stay: readable.

The module had no suite until a real migration was run against a real version 1 project — `warbook`,
generated by 1.6.2, migrated to 2.0.0.dev0 — and the page it wrote had a fifteen-hundred-word paragraph in
it. Forty-two fragments, each written by whoever made that one change, with their claims concatenated into
one sentence and their catch-up paragraphs into another, so that *"...so `./init` offers them. nothing for
a consumer. A publisher: `slipwai package new` writes the whole repository. nothing. The first install
from a named publisher asks you once."* ran together with nothing saying which change any of it belonged
to.

Nothing was wrong with what it said. `in_flight` is right that a project owes all of a release and not the
first of it, and nothing here summarises or infers — that rule is the module's and it still holds. What
was wrong was that the two halves of each fragment were read apart and joined separately, so the thing a
reader needs to act — *this change asks this of you* — was the one thing the page had thrown away.

So the tests that matter here are about pairing and about shape: every fragment gets its own line, each
line names its own change, and a fragment that wrote no catch-up paragraph is said to have written none
rather than being dropped or read as asking nothing.
"""
from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

import checkout_packages  # noqa: F401

from slipwai import catch_up

FRAGMENT = """{level}

**{claim}** What it changed, at whatever length the author wanted, wrapped across
lines the way the changelog wraps its prose.
{note}"""
NOTE = "\n**Catch-up:** {owed}\n"


def written(root: Path, name: str, claim: str, owed: str | None, level: str = "MINOR") -> None:
    directory = root / "changelog.d"
    directory.mkdir(parents=True, exist_ok=True)
    (directory / f"{name}.md").write_text(
        FRAGMENT.format(level=level, claim=claim, note="" if owed is None else NOTE.format(owed=owed)),
        encoding="utf-8",
    )


class InFlightTest(unittest.TestCase):
    """A release still being written: its entry is its fragments, a line each."""

    def setUp(self) -> None:
        self.root = Path(tempfile.mkdtemp())
        (self.root / "CHANGELOG.md").write_text("# Changelog\n", encoding="utf-8")

    def entry(self) -> catch_up.Entry:
        found = catch_up.in_flight(self.root, "3.1.0.dev2")
        self.assertEqual(len(found), 1, "the release in flight has no entry")
        return found[0]

    def test_the_entry_is_the_release_the_snapshot_is_heading_for(self) -> None:
        written(self.root, "a-first", "The first thing.", "`slipwai migrate`.", level="MAJOR")
        number, level, _claim, _owed = self.entry()
        self.assertEqual((number, level), ("3.1.0", "MAJOR"))

    def test_every_fragment_owes_on_a_line_of_its_own_naming_its_own_change(self) -> None:
        """The whole of the defect: which change is asking is the one thing a reader needs."""
        written(self.root, "a-first", "The first thing.", "Run `slipwai migrate`.")
        written(self.root, "b-second", "The second thing.", "nothing for a consumer.")
        _number, _level, claim, owed = self.entry()
        self.assertEqual(owed, "- **The first thing.** Run `slipwai migrate`.\n"
                               "- **The second thing.** nothing for a consumer.")
        self.assertEqual(claim, "- The first thing.\n- The second thing.")

    def test_a_fragment_with_no_catch_up_paragraph_is_said_to_have_written_none(self) -> None:
        """Not dropped, and not read as asking nothing: that would be a promise this cannot make."""
        written(self.root, "a-first", "The first thing.", None)
        _number, _level, _claim, owed = self.entry()
        assert owed is not None
        self.assertIn("The first thing.", owed)
        self.assertIn("no catch-up paragraph", owed)

    def test_a_fragment_with_no_claim_is_still_a_line(self) -> None:
        (self.root / "changelog.d").mkdir(parents=True, exist_ok=True)
        (self.root / "changelog.d/a-bare.md").write_text(
            "MINOR\n\nNo claim in bold anywhere.\n\n**Catch-up:** Run it twice.\n", encoding="utf-8")
        _number, _level, claim, owed = self.entry()
        assert owed is not None
        self.assertIn("Run it twice.", owed)
        self.assertIn(catch_up.NO_CLAIM, owed)
        self.assertEqual(claim, "(the fragments for this version state no headline)")

    def test_no_fragments_is_no_entry_rather_than_an_empty_one(self) -> None:
        self.assertEqual(catch_up.in_flight(self.root, "3.1.0.dev2"), [])

    def test_a_release_already_in_the_changelog_is_not_also_in_flight(self) -> None:
        """Otherwise a project would be told twice, once from the fragments and once from the entry."""
        written(self.root, "a-first", "The first thing.", "Run it.")
        (self.root / "CHANGELOG.md").write_text(
            "# Changelog\n\n## 3.1.0 — MINOR\n\n**The first thing.**\n\n**Catch-up:** Run it.\n",
            encoding="utf-8")
        self.assertEqual(catch_up.in_flight(self.root, "3.1.0.dev2"), [])


class ListingTest(unittest.TestCase):
    """How an entry is printed, which differs by how many lines it has rather than by where it came from."""

    def test_a_released_entrys_one_paragraph_stays_on_the_line_that_introduces_it(self) -> None:
        said = catch_up.listing([("1.2.0", "MINOR", "It changed.", "Run `slipwai migrate`.")])
        self.assertIn("**Owes:** Run `slipwai migrate`.", said)

    def test_a_list_starts_below_the_words_that_introduce_it(self) -> None:
        """`**Owes:** - a` is not a list in any Markdown renderer, and this page is read rendered."""
        said = catch_up.listing([("2.0.0", "MAJOR", "- a\n- b", "- **a** Run it.\n- **b** nothing.")])
        self.assertIn("**Owes:**", said)
        self.assertNotIn("**Owes:** - **a** Run it.", "\n".join(said))
        self.assertEqual(said[said.index("**Owes:**") + 1], "")

    def test_an_entry_whose_author_wrote_nothing_says_that_and_not_nothing(self) -> None:
        said = catch_up.listing([("1.2.0", None, "It changed.", None)])
        self.assertIn("**Owes:** nothing recorded for a repository that already existed.", said)


class ShippedTest(unittest.TestCase):
    """The keel's own fragments, which is the release this was found on."""

    def test_the_release_in_flight_renders_one_line_per_fragment(self) -> None:
        found = catch_up.in_flight()
        if not found:  # pragma: no cover - between a release being cut and the next fragment
            self.skipTest("no release is in flight in this checkout")
        _number, _level, claim, owed = found[0]
        assert owed is not None
        from slipwai import changelog  # noqa: PLC0415
        self.assertEqual(len(owed.splitlines()), len(changelog.fragments(tolerant=True)))
        self.assertEqual(len(claim.splitlines()), len(changelog.fragments(tolerant=True)))
        for line in owed.splitlines():
            with self.subTest(line=line[:60]):
                self.assertTrue(line.startswith("- **"), "a line does not name the change it belongs to")


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
