"""Reading `project.json` back: the applications a generated project records, as `services.App`.

Split from `services.py` when that module reached its budget. `services` says what the list of applications
*is* and what every project-wide file derives from it; this module is the one reader that turns the written
manifest back into that list — for `add-service`, which grows a project that already exists, and `replay`,
which emits the whole project again from a newer factory — and the one place a manifest this keel does
not understand is refused.
"""
from __future__ import annotations

import json
from pathlib import Path, PurePosixPath

from ..assets import this_command
from ..axes import named_axes
from ..catalog import CATALOG, families
from ..errors import GenerationError
from ..loaded import refusals
from ..npm_workspace import npm
from ..registry import registry
from ..selection import Selection
from ..services import App, services_of, wrapped_of
from .languages import answered, loaded_versions, recorded_languages, refuse_unreadable

# What a manifest has to say for a command to reproduce the generation it came from. Everything else in it
# is carried through untouched, so a field a later factory adds survives an `add-service` by an older one.
REQUIRED = ("name", "profile", "frontend", "target", "deployables")

# The `project.json` shape this keel reads and writes. A project whose manifest says another number was
# generated by a factory that meant something else by these fields, and `add-service` refuses it rather
# than guessing.
MANIFEST_SCHEMA = 2

# Where a recorded fact came from, for an application the keel described rather than chose. How the
# repository itself came to have the keel's material is `origin.py`.
# `unrecorded` is the written form of "nobody has said": a fact `adopt --yes` could not read off the tree and
# nobody was asked about, kept visibly open rather than defaulted, and refreshed by the next survey that can say.
PROVENANCES = ("detected", "confirmed", "overridden", "unrecorded")



def recorded_contexts(record: dict) -> tuple[str, ...]:
    """A service's `contexts` as the manifest records them — or the one `context` a manifest written before
    a service could hold several named, read as a list of one so nothing generated then has to change."""
    contexts = record.get("contexts", [record["context"]] if "context" in record else [])
    if not isinstance(contexts, list) or not all(isinstance(name, str) for name in contexts):
        raise TypeError("'contexts' as a list of names")
    return tuple(contexts)


def wrapped_commands(record: dict) -> dict[str, str | None] | None:
    """An existing application's `commands`: one per Make target its own build answers, None for a written no."""
    commands = record.get("commands")
    if commands is None:
        return None
    if not isinstance(commands, dict) or not all(
        isinstance(target, str) and (command is None or isinstance(command, str))
        for target, command in commands.items()
    ):
        raise TypeError("'commands' as a map from Make target to command or null")
    return dict(commands)


def recorded_toolchain(record: dict) -> dict[str, str] | None:
    """What a wrapped application's build runs on, as recorded: a map of strings, or nothing."""
    toolchain = record.get("toolchain")
    if toolchain is None:
        return None
    if not isinstance(toolchain, dict) or not all(
        isinstance(k, str) and isinstance(v, str) for k, v in toolchain.items()
    ):
        raise TypeError("'toolchain' as a map of strings")
    return dict(toolchain)


def recorded_structure(record: dict) -> str | None:
    """A wrapped application's declared `layout` — `hexagonal` puts the import gate's rules on it — or nothing."""
    structure = record.get("layout")
    if structure is not None and structure != "hexagonal":
        raise TypeError("'layout' as \"hexagonal\", or absent")
    return structure


def recorded_provenance(record: dict) -> dict[str, str]:
    """Where each of an application's facts came from, as recorded; nothing where the manifest says nothing."""
    provenance = record.get("provenance", {})
    if not isinstance(provenance, dict) or not all(
        isinstance(name, str) and origin in PROVENANCES for name, origin in provenance.items()
    ):
        raise TypeError(f"'provenance' as a map from field to one of {', '.join(PROVENANCES)}")
    return dict(provenance)


def apps_from_manifest(document: dict, allow_empty: bool = False) -> list[App]:
    """The applications a `project.json` records, refusing a manifest this keel does not understand.

    An application recorded `"generated": false` already existed when the method was installed around it:
    it is carried as written — its language, its commands, where its facts came from — and asked nothing a
    generated one is asked, which is why it needs no port and no selection.

    `allow_empty` is for the readers of an adopted repository between `adopt` and its first confirmed
    candidate (ADR 0003), where no deployable is the honest state rather than a broken manifest. It stays off
    for `add-service`, which needs one to take a language and a port from, and whose refusal this was.
    """
    if document.get("schema") != MANIFEST_SCHEMA:
        raise GenerationError(
            f"project.json has schema {document.get('schema')!r}, and this factory reads schema "
            f"{MANIFEST_SCHEMA}: it was generated by a factory that means something else by these fields"
        )
    deployables = document.get("deployables")
    if not isinstance(deployables, dict) or (not deployables and not allow_empty):
        # An adopted repository between `adopt` and its first confirmed candidate has no deployable *yet*,
        # which is a different thing from a manifest that names none — and the difference is what somebody
        # has to do next. The first real adoption to hit this was told to "add a service" by `add-frontend`,
        # having just been told by `./init` to run `slipwai add-frontend web`, with no way to know that
        # confirming a candidate was the missing step.
        outstanding = document.get("candidates")
        if isinstance(outstanding, list) and outstanding:
            named = ", ".join(
                str(row.get("name")) for row in outstanding if isinstance(row, dict) and row.get("name")
            )
            raise GenerationError(
                "project.json records no application yet — the survey found "
                f"{len(outstanding)} buildable director{'y' if len(outstanding) == 1 else 'ies'} and nobody "
                f"has said which of them is one: {named}. `/ground` asks, and `slipwai adopt --confirm "
                "<name>` records the answer; this command needs an application to sit beside."
            )
        raise GenerationError("project.json names no deployables, so there is nothing to add a service to")
    refuse_unreadable(document)
    apps: list[App] = []
    for name, record in deployables.items():
        try:
            generated = record.get("generated", True)
            if generated is not True and generated is not False:
                raise TypeError("'generated' as true or false")
            service = record["kind"] == "service"
            selection = record.get("selection", {}) if service and generated else {}
            if not isinstance(selection, dict):
                raise TypeError("'selection'")
            apps.append(
                App(
                    name,
                    record["path"],
                    record["kind"],
                    record["language"],
                    record.get("framework"),
                    int(record["port"]) if generated else int(record.get("port", 0)),
                    # Read under the names this keel now uses, so a project generated before an
                    # axis was renamed replays without being migrated first (`axes.RENAMED`).
                    Selection(named_axes(selection)),
                    record.get("api") if not service else None,
                    purpose=record.get("purpose") if service or not generated else None,
                    contexts=recorded_contexts(record) if service or not generated else (),
                    first=generated and all(app.kind != record["kind"] for app in apps if app.generated),
                    generated=generated,
                    commands=wrapped_commands(record) if not generated else None,
                    toolchain=recorded_toolchain(record) if not generated else None,
                    structure=recorded_structure(record) if not generated else None,
                    provenance=recorded_provenance(record),
                )
            )
        except (KeyError, TypeError, ValueError) as error:
            raise GenerationError(
                f"project.json's deployable '{name}' is missing {error}, which schema {MANIFEST_SCHEMA} "
                "requires"
            ) from error
    if not services_of(apps) and not wrapped_of(apps) and not (allow_empty and not apps):
        raise GenerationError("project.json records no service, only a browser app")
    refuse_missing_languages(apps, recorded_languages(document))
    return apps


def refuse_missing_languages(apps: list[App], recorded: dict[str, str] | None = None) -> None:
    """One refusal naming every language the project needs and this install has not loaded, with its install line.

    A service names a family and a backend the registry must hold; a browser app names a family that must answer the
    npm workspace. Checked together, before any part asks either for an answer, so a maintainer learns of every
    missing language in one round and not one per run (C001, G001). The install line is the one every refusal for a
    missing language names, `language install` as this copy is typed here (FR-015, SC-004). Where the project records
    its packages (`recorded`, ADR 0005) the line names each of them that is not loaded — `java-quarkus`, not only
    `java` — in one command; a 1.x project with no record names each family the same way. A package that is in the
    package directory but refused by the loader is named as refused, with the loader's own line, never as missing
   .
    """
    held, backends = families(), CATALOG["backends"]
    have = {*loaded_versions(), *registry().families}
    needed: dict[str, list[str]] = {}
    unfit: list[str] = []
    for app in apps:
        if not app.generated:
            continue
        if app.is_service and (app.language not in held or not answered(app, backends)):
            needed.setdefault(app.language, []).append(f"the service {app.name}")
        elif not app.is_service and not npm(app.language):
            if app.language in have:  # installed, so an install line would not help: it answers no npm workspace
                unfit.append(f"the browser app {app.name} is recorded as {app.language}, which is installed and "
                             "answers no npm workspace")
            else:
                needed.setdefault(app.language, []).append(f"the browser app {app.name}")
    if not needed and not unfit:
        return
    lines = {line.split(" ", 2)[1]: line for line in refusals() if line.startswith("language ")}
    absent = [] if not needed else (
        list(needed) if recorded is None else [name for name in recorded if name not in have] or list(needed))
    # A language installed and refused is not unknown: its own line, which names the fix, says it.
    parts = [f"unknown language '{language}' for {' and '.join(holders)}" for language, holders in needed.items()
             if not (language in lines and language in absent)]
    refused = [f"{name} is installed and the loader refused it — {lines[name]}" for name in absent if name in lines]
    missing = [name for name in absent if name not in lines]
    install = f": {this_command()} language install {' '.join(missing)}" if missing else ""
    raise GenerationError("; ".join([*parts, *unfit, *refused]) + install)


def fault(root: Path, path: object) -> str | None:
    """What is wrong with a path `project.json` gave, in the words a refusal uses, or `None` where it is relative,
    holds no `..`, and resolves — links included — inside `root` and outside `.git`. The root itself is allowed
    only spelled as `.`, which is where an adopted application lives."""
    if not isinstance(path, str):
        return "which is not a string"
    pure = PurePosixPath(path)
    if not path:
        return "which is empty"
    if "\0" in path:
        return "which holds a NUL byte"
    if pure.is_absolute() or ".." in pure.parts or "\\" in path:
        return "which is outside this project"
    resolved, anchor = (root / path).resolve(), root.resolve()
    if resolved == anchor and pure != PurePosixPath("."):
        return "which is the project itself"
    if not resolved.is_relative_to(anchor):
        return "which is outside this project"
    if resolved.relative_to(anchor).parts[:1] == (".git",):
        return "which is under `.git`"
    return None


def contained(root: Path, path: str) -> bool:
    """Whether a path `project.json` gave is relative, holds no `..`, and resolves — links included — strictly
    inside `root`."""
    return fault(root, path) is None


def refuse_outside(root: Path, document: dict) -> None:
    """Refuse a deployable whose `path` is absolute, holds `..`, or resolves outside the project (D31, scenario 12):
    every verb that writes or prunes under it would reach out of the project."""
    deployables = document.get("deployables")
    layout = document.get("layout")
    delivery = layout.get("delivery", ".") if isinstance(layout, dict) else "."
    reason = None if delivery == "." else fault(root, delivery)
    if reason:
        raise GenerationError(f"project.json's layout.delivery is {delivery!r}, {reason}: "
                              "it is `.` or a directory inside the project root")
    for name, record in (deployables.items() if isinstance(deployables, dict) else []):
        if not isinstance(record, dict) or "path" not in record:
            continue
        path = record["path"]
        reason = fault(root, path)
        if reason:
            raise GenerationError(f"project.json's deployable '{name}' has the path {path!r}, {reason}: "
                                  "a deployable's path is relative to the project root and stays inside it")


def read_manifest(root: Path, verb: str = "add-service") -> dict:
    """The project's `project.json`, or the refusal that says why this directory is not a generated project."""
    manifest = root / "project.json"
    if not manifest.is_file():
        raise GenerationError(
            f"there is no project.json in {root}, so this is not the root of a project this factory "
            f"generated — run {verb} from that directory"
        )
    try:
        document = json.loads(manifest.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise GenerationError(f"project.json is not valid JSON: {error}") from error
    if not isinstance(document, dict):
        raise GenerationError("project.json is not an object")
    missing = [key for key in REQUIRED if key not in document]
    if not missing:
        refuse_outside(root, document)
    if missing:
        raise GenerationError(
            f"project.json has no {', '.join(missing)}, which this factory needs to reproduce the generation "
            "it came from — it was written by a factory that means something else by this file"
        )
    return document


def check_known(apps: list[App]) -> None:
    """Every service's backend and every answer in its selection has to be one this catalog has."""
    for service in services_of(apps):
        if service.backend not in CATALOG["backends"]:
            raise GenerationError(
                f"project.json's service '{service.name}' names the backend {service.backend!r}, which this "
                f"factory does not offer; it knows {', '.join(CATALOG['backends'])}"
            )
        for axis, chosen in service.selection.choices.items():
            if axis not in CATALOG["axes"] or chosen not in CATALOG["axes"][axis]["options"]:
                raise GenerationError(
                    f"project.json's service '{service.name}' answers {axis} with {chosen!r}, which this "
                    "factory does not know — it was written by a factory with a different catalog"
                )
