/**
 * The event-model section a project's README carries, generated from the model.
 *
 * ── Why the README and not just `docs/event-model/` ───────────────────────────────────────────────────
 * The README is the one file everybody opens. A model nobody sees is a model nobody notices has gone
 * stale, and the diagram's whole purpose is to answer "what does this event already mean, and who reads
 * it" *before* a new slice commits to an answer. So `make model` keeps a block in the README current, and
 * `make check-model` fails when it drifts — the same treatment the committed SVG already gets, for the
 * same reason.
 *
 * ── Opt-in by markers ─────────────────────────────────────────────────────────────────────────────────
 * The block is written only between the two markers below. A README without them is left completely
 * alone, and neither generating nor checking says a word about it. That matters because this template's
 * own README is inherited by every project generated from it: a project that does not want the section
 * deletes the markers, and nothing nags.
 *
 * Everything here is pure so it can be tested without a repository, a browser, or a filesystem.
 */
import { segmentModel, segmentRange, type Model, type Segment, type Status } from './model.ts';
import { MODEL_DIR, MODEL_HTML, MODEL_SOURCE, MODEL_SVG, segmentArtifact } from './workspace.ts';

export const README_START = '<!-- event-model:start -->';
export const README_END = '<!-- event-model:end -->';

/**
 * Reported most-advanced first, and only when non-zero, so the line reads as progress rather than a census.
 *
 * Not `model.ts`'s `STATUS_ORDER`: that one ranks statuses for the gates ("is this at least `planned`?")
 * and runs the other way. Two orders, two jobs — named differently so neither gets swapped in for the other.
 */
const REPORT_ORDER: readonly Status[] = ['implemented', 'planned', 'modelled', 'proposed'];

function countByStatus(model: Model): string {
  const counts = new Map<Status, number>();
  for (const slice of model.slices) {
    counts.set(slice.status, (counts.get(slice.status) ?? 0) + 1);
  }
  return REPORT_ORDER.filter((status) => (counts.get(status) ?? 0) > 0)
    .map((status) => `${String(counts.get(status))} ${status}`)
    .join(', ');
}

const forwardSlashed = (path: string): string => path.split('\\').join('/');

/**
 * One segment as a heading and a linked image.
 *
 * The image is wrapped in a link to itself, which is the only escape a README reader has: a forge scales
 * an image into a fixed column and offers no zoom, so without the link a diagram a little too wide is
 * simply unreadable with no way to find out what it said.
 */
function segmentBlock(model: Model, segment: Segment): string[] {
  const names = segment.sliceIds
    .map((id) => model.slices.find((slice) => slice.id === id)?.name ?? id)
    .join(', ');
  const alt = `${segmentRange(segment)}: ${names}`;
  const svg = forwardSlashed(segmentArtifact(segment.index, 'svg'));

  return [`### ${segmentRange(segment)}`, '', `[![${alt}](${svg})](${svg})`, ''];
}

/**
 * The section's body, between the markers but not including them.
 *
 * Paths are repository-relative because that is what renders on a forge: the README sits at the root, so
 * `docs/event-model/model.svg` resolves for a reader on the web and for one with a local clone. The one
 * absolute URL is `render.page`, which is absolute because it names a site rather than a file.
 */
export function renderReadmeSection(model: Model): string {
  const generated = `<!-- Generated by \`make model\` from ${MODEL_SOURCE}. Do not edit this block by hand. -->`;

  if (model.slices.length === 0) {
    return [
      generated,
      '',
      '## Event model',
      '',
      'No slices yet — which is the correct state until the first modelling conversation, not a gap to',
      'fill in. An event schema is permanent and stream identity cannot be migrated, so this model ships',
      'empty rather than guessing at either.',
      '',
      'Model your first workflow with the `event-modeling` skill, then run `make model`.',
    ].join('\n');
  }

  const total = model.slices.length;
  const noun = total === 1 ? 'slice' : 'slices';
  const segments = segmentModel(model);
  const source = forwardSlashed(MODEL_SOURCE);
  const dir = forwardSlashed(MODEL_DIR);
  const page = model.render.page;

  // Published: the link replaces the diagrams rather than sitting above them. A segment SVG scaled into a
  // README column has no zoom, no slice register and no per-slice view, so once the better version has an
  // address, embedding the worse one only adds the part of the section nobody reads. Thirteen slices came
  // out as nine of those images stacked above a link to the page that showed all of it properly.
  //
  // `model.svg` stays linked as text. It is the right thing on a big screen, and dropping the embed should
  // not also drop the one artifact a reader with a clone and no network can open.
  if (page !== undefined) {
    return [
      generated,
      '',
      '## Event model',
      '',
      `**${String(total)} ${noun} on one timeline** — ${countByStatus(model)}. The source is`,
      `[\`${source}\`](${source}); everything below is generated from it.`,
      '',
      `**[Browse the model](${page})** — the whole timeline, the slice register, and each slice on its own,`,
      'in one page. Published on every change to the model or the renderer, so it is never the stale copy.',
      '',
      `[The whole timeline in one SVG](${forwardSlashed(MODEL_SVG)}) · [\`${dir}/README.md\`](${dir}/README.md) for the format and the four slice patterns.`,
      '',
      '`make check-model` refuses a model that disagrees with the code — a slice reading an event nothing',
      'produces, an implemented slice naming an event absent from the source, a slice planned before its',
      'examples exist. Regenerate with `make model` and commit the result.',
    ].join('\n');
  }

  // One segment is the whole timeline, so it needs no heading and no explanation of why it is in pieces.
  const diagrams =
    segments.length === 1
      ? [`[![Global event model](${forwardSlashed(segmentArtifact(1, 'svg'))})](${forwardSlashed(MODEL_SVG)})`, '']
      : [
          `The timeline is in ${String(segments.length)} segments so each one stays legible at this width —`,
          'read them in order; together they are the one model. Click a segment to open it full size.',
          '',
          ...segments.flatMap((segment) => segmentBlock(model, segment)),
        ];

  return [
    generated,
    '',
    '## Event model',
    '',
    `**${String(total)} ${noun} on one timeline** — ${countByStatus(model)}. The source is`,
    `[\`${source}\`](${source}); every diagram here is generated from it.`,
    '',
    ...diagrams,
    `[The whole timeline in one SVG](${forwardSlashed(MODEL_SVG)}) · [\`${dir}/README.md\`](${dir}/README.md) for the format and the four slice patterns.`,
    '',
    // Without a page the browsable copy exists only in a clone, and saying so is the difference between a
    // useful link and one that serves a wall of markup: a forge serves .html as source, not as a page.
    `\`${forwardSlashed(MODEL_HTML)}\` is the browsable version — the timeline, the slice register, and each`,
    'slice on its own, in one page. Open it from a clone: a forge serves HTML as source, not as a page.',
    '',
    '`make check-model` refuses a model that disagrees with the code — a slice reading an event nothing',
    'produces, an implemented slice naming an event absent from the source, a slice planned before its',
    'examples exist. Regenerate with `make model` and commit the result.',
  ].join('\n');
}

/** Where the block sits in a README, or why it does not. */
export type BlockLocation =
  | { readonly present: true; readonly before: string; readonly body: string; readonly after: string }
  | { readonly present: false; readonly reason: 'absent' | 'malformed' };

/**
 * Locate the block without rewriting anything.
 *
 * `malformed` is kept distinct from `absent` on purpose: a README with an end marker and no start, or the
 * two in the wrong order, is a mistake worth reporting, whereas a README with neither is a deliberate
 * choice to not carry the section.
 */
export function locateReadmeBlock(readme: string): BlockLocation {
  const start = readme.indexOf(README_START);
  const end = readme.indexOf(README_END);

  if (start === -1 && end === -1) return { present: false, reason: 'absent' };
  if (start === -1 || end === -1 || end < start) return { present: false, reason: 'malformed' };

  return {
    present: true,
    before: readme.slice(0, start + README_START.length),
    body: readme.slice(start + README_START.length, end),
    after: readme.slice(end),
  };
}

/**
 * The README as it should be, or `undefined` when it carries no usable block.
 *
 * Returning `undefined` rather than appending is what makes this safe to run on any README: the generator
 * never invents a section, and never guesses where one should go.
 */
export function withReadmeSection(readme: string, section: string): string | undefined {
  const located = locateReadmeBlock(readme);
  if (!located.present) return undefined;
  return `${located.before}\n${section}\n${located.after}`;
}

/** Does the README already say exactly what the model implies? */
export function readmeSectionIsCurrent(readme: string, section: string): boolean {
  const located = locateReadmeBlock(readme);
  if (!located.present) return false;
  return located.body === `\n${section}\n`;
}
