"""`docs/design.md`: what this project's browser surface looks like, and where that is decided.

A page rather than a comment in the stylesheet, because it is read by somebody who has not opened the
stylesheet yet — the next slice with a screen in it. The baseline the skeleton ships is deliberately
generic, and the point of this page is to say so out loud and to be the one place a project records what
it chose instead.

Written only for a project that has a browser app: a repository with no frontend has no design to decide,
and a page describing one would be a page that never becomes true.
"""
from __future__ import annotations

from ..services import App, services_of, web_apps
from .openapi import document_of

DESIGN = "docs/design.md"


def data_layer(apps: list[App]) -> str:
    """How the one route talks to this project's API, and — where it is by hand — why.

    The absence of a generated client is the kind of thing a reader finds by opening the directory and
    concluding the keel forgot, so it is written down where somebody about to write a screen is
    already looking. It is not a gap in the frontend: it is what a transport that publishes no document
    costs, stated at the place the cost lands.
    """
    api = next((service for service in services_of(apps) if service.transport is not None), None)
    if api is None:
        return ""
    if document_of(api) is not None:
        return f"""
## Talking to this project's API

The one route calls the service through `packages/api-client`, whose types are generated by
`make build-packages` from `{document_of(api)}` — the document `make openapi` writes out of the routes
themselves. So a field a screen reads is a field the contract declares, and a route renamed in the service
stops the browser app compiling instead of failing in front of somebody. Never edit the generated
`packages/api-client/src/schema.ts`; it is a build output and `.gitignore` refuses it.
"""
    return f"""
## Talking to this project's API — by hand, and why

`{api.path}` publishes no API document, so there is nothing to generate a client from and this project has
no `packages/api-client`. `{web_apps(apps)[0].path}/src/routes/Home.tsx` fetches by hand, and the response
is typed `Record<string, unknown>` — the honest thing to say about a shape nobody declared. A field read
off it is a field the compiler cannot check.

That is a cost, not a style. The way out is to publish a document: this backend's framework has an OpenAPI
extension, and adding it is the change that makes a typed client possible. When it lands, the service gains
a committed `openapi.json` and a `make check-openapi` that holds it to the routes, and this page's
counterpart in a project that has one describes what replaces the hand-written fetch.
"""


def design_page(apps: list[App]) -> dict[str, str]:
    """The page, or nothing at all where this project has no browser surface."""
    web = web_apps(apps)
    if not web:
        return {}
    app = web[0].path
    return {DESIGN: f"""# Design

What this project's screens look like, and where each of those decisions lives. **Every slice with a
browser surface reads this page first**, and changes it in the same commit as the screens it affects.

## What was generated

`{app}` ships a working baseline rather than browser defaults: design tokens, a layout shell, and styled
versions of the elements a browser already renders. That is not a design — it is a floor. A first slice
demonstrated on an unstyled page gets feedback about the page, and the point of a walking skeleton is
feedback about the slice.

| File | What it holds |
|---|---|
| `{app}/src/styles/tokens.css` | Every value the look is made of: colour by role, a type scale, a spacing scale, radii, the reading measure. Light and dark. |
| `{app}/src/styles/base.css` | The page built out of those tokens: the shell, and element styles for headings, links, buttons, form controls and tables. |
| `{app}/src/App.tsx` | The shell itself — header, main, footer — and the routing table. |

Both stylesheets are imported once, from `{app}/src/main.tsx`. Nothing else imports them.
{data_layer(apps)}
## Replace these with the brand's values

The palette is one neutral ramp and one accent, chosen to be unobjectionable and to be replaced. Change
the values in `tokens.css` — not the names — and every screen follows, because nothing below the tokens
holds a literal colour or size. Then write down here what was chosen and why, so the next person does not
have to reverse-engineer it from hex codes:

- **Colour.** What the accent is, what it means, and which pair carries a positive or negative outcome.
  Check the text/background contrast of anything that changes: the tokens ship at 4.5:1 or better in both
  schemes, and a brand colour dropped in without checking is the commonest way that is lost.
- **Type.** The family, and whether the four steps are enough. A fifth step is a decision; add it here.
- **Spacing and shape.** The scale exists so a gap is chosen from a list rather than invented per
  component. Keep it a list.
- **Dark mode.** Only the colour tokens are redefined under `prefers-color-scheme: dark`. Anything added
  as a literal colour breaks that, silently, for half the people who open it.

## Rules a slice follows

- **Use the elements.** A slice that writes `<button>` gets this project's button. Reach for a class only
  where the element does not exist.
- **Use the tokens.** A literal colour or pixel value in a slice's CSS is a value nobody can change
  centrally, and the first place a redesign gets stuck.
- **Keep the shell.** Header, main and footer are the page; a screen is what goes inside `main`.
- **No framework, no runtime dependency.** Plain CSS files. A CSS framework decides far more than colour
  for a project that has not decided anything, and it is the first dependency spent on what a stylesheet
  already does.
- **Accessibility is part of the design, not a pass afterwards.** Real landmarks (`header`, `main`,
  `footer`, `nav`), a visible focus ring — `base.css` sets one — labels on controls, and a status message
  in a `role="status"` region so a change is announced rather than only seen.
- **Decide before you build.** The first screen of a slice that this page has no decision for starts with
  `skills/frontend-design`: a compact plan — palette, type, layout, principles — reviewed against the brief
  for generic defaults before any code, then written into `tokens.css` and recorded here in the same commit.
- **Review before you demo.** Every file the slice added or changed under the browser app is read against
  `skills/web-interface-guidelines` — labels, focus, forms, motion, typography, the anti-patterns — and what
  it finds is fixed before the demo stop, not carried as a note. Where the rules and this page disagree,
  this page wins.
""" }


def existing_design_page(
    apps: list[App], token_paths: list[str], styled_apps: list[str]
) -> str:
    """The design page replay offers when the project has replaced the generated baseline.

    The project files are evidence, not a guess from names: each path here is an imported stylesheet with
    custom properties at ``:root``. The starter paths must not survive in the page after replay removes
    their untouched files, because this is the first page every browser slice is told to read.
    """
    tokens = "\n".join(f"- `{path}`" for path in token_paths)
    locations = ", ".join(f"`{path}`" for path in styled_apps)
    return f"""# Design

What this project's screens look like, and where each of those decisions lives. **Every slice with a
browser surface reads this page first**, and changes it in the same commit as the screens it affects.

## The project's design system

This project replaced the generated visual baseline. Its imported root tokens are owned here:

{tokens}

Those files, and the stylesheets that consume them, are the authority. The factory's
two baseline stylesheets are deliberately absent from {locations}: two imported token systems make bundle
order decide the design, and neither stylesheet can reveal that collision by itself.
{data_layer(apps)}
## Record the decisions

Keep this page beside the implementation as the explanation a stylesheet cannot carry alone:

- **Colour.** What the palette means, including contrast requirements and dark-mode behaviour.
- **Type.** Which families and scale the product uses.
- **Spacing and shape.** Which scales are shared rather than invented per component.
- **Components and layout.** Where the shell and reusable visual primitives live.

## Rules a slice follows

- Use the project's imported tokens rather than introducing another global token file.
- Keep literal colours and dimensions at the level this design system expects, so a redesign still has one
  place to act.
- Follow the existing shell and component vocabulary; a slice does not introduce a second one casually.
- Accessibility is part of the design: preserve landmarks, focus visibility, labels, contrast and status
  announcements while changing the screen.
"""
