"""One file per event, and an index nobody writes: the two merges that never meet on a line.

Two slices in one context both add an event. In version 1 both edited `events.py`, both added a class at
the end of it, and the merge was a conflict in the same three lines — every time, for every pair, in a
file that only ever grows. The resolution is always "take both", which is the definition of a conflict that
should not have been one.

**So an event is a file, named after the mark that declares it.** Two additions are two new files, and git
merges two new files without being asked anything. Nothing else about the layout changes: the files sit
where the backend's `events` path already pointed, in a directory of that name rather than a module of it.

**And the index is generated, never written.** Something has to import the files or the language cannot see
them, and a hand-written index is the shared line again with an extra step. `make events` writes it from
what is on disk, and `make check-events` refuses one that is not what the files render to — the pattern
`scripts/glossary.py --check` has used since slice 1.6, and `render-fairways` since 5.10b.

**The import line is the language's, not the framework's.** A Python index re-exports with `from . import`,
a TypeScript one with `export *`, and a Go package needs no index at all because the directory *is* the
namespace. That is a property of the language, so it is keyed by file extension here rather than being a
protocol member six packages would each have to answer with the same string.
"""
from __future__ import annotations

from pathlib import PurePosixPath

#: How each language re-exports one event file from the index, keyed by the extension the backend writes.
#: A language absent from here gets no index, which is right for Go and anything else where a directory is
#: already a namespace — the one-file-per-event rule still holds and there is simply nothing to generate.
INDEX_LINE = {
    ".py": "from .{stem} import *  # noqa: F403",
    ".ts": 'export * from "./{stem}";',
    ".tsx": 'export * from "./{stem}";',
    ".kt": "",
    ".java": "",
    ".go": "",
}
#: What the generated index is called, per extension. `__init__.py` is Python's; everything else is `index`.
INDEX_NAME = {".py": "__init__.py", ".ts": "index.ts", ".tsx": "index.ts"}
BANNER = {
    ".py": '"""Generated by `make events` from the files beside it. Never edit: `make check-events` refuses\na hand-written index, because a shared line is the merge conflict one file per event exists to remove.\n"""',
    ".ts": "// Generated by `make events` from the files beside it. Never edit: `make check-events` refuses\n// a hand-written index, because a shared line is the merge conflict one file per event exists to remove.",
}


def events_directory(events_path: str) -> str:
    """The directory events live in, from the backend's `events` answer.

    A backend that says `.../events.py` means a module today and a directory from this slice on, so the
    suffix is dropped rather than a second protocol answer being asked for. A backend already naming a
    directory is left alone.
    """
    path = PurePosixPath(events_path)
    return str(path.with_suffix("")) if path.suffix else events_path


def event_file(events_path: str, mark: str) -> str:
    """Where one event's file goes: the directory, and the mark's own name.

    Named after the mark rather than after anything derived from it, so the chart, the log line and the
    file all say one word. A reader who greps the mark finds the file.
    """
    suffix = PurePosixPath(events_path).suffix or ".py"
    return f"{events_directory(events_path)}/{mark}{suffix}"


def index_path(events_path: str) -> str | None:
    """Where the generated index goes, or `None` for a language that needs none."""
    suffix = PurePosixPath(events_path).suffix or ".py"
    name = INDEX_NAME.get(suffix)
    return f"{events_directory(events_path)}/{name}" if name else None


def index(events_path: str, marks: list[str]) -> str | None:
    """The index these events render to, or `None` where the language needs no index.

    Sorted, so two slices adding an event produce one index whichever order they merged in — which is the
    whole point: the merge of two additions is a regeneration, not a resolution.
    """
    suffix = PurePosixPath(events_path).suffix or ".py"
    line = INDEX_LINE.get(suffix)
    if not line or suffix not in INDEX_NAME:
        return None
    body = "\n".join(line.format(stem=mark) for mark in sorted(marks))
    banner = BANNER.get(suffix, "")
    return f"{banner}\n\n{body}\n" if banner else f"{body}\n"


def event_marks(chart: dict) -> list[str]:
    """Every event the chart declares. The chart is the source, because it is what both profiles have."""
    marks = chart.get("marks")
    if not isinstance(marks, dict):
        return []
    return sorted(name for name, body in marks.items()
                  if isinstance(body, dict) and body.get("kind") == "event")
