"""The composition root's slice wiring: generated from the chart, inside a region nobody edits.

The composition root is the second file every slice touched. Each one added a line wiring its own use case
into the application, all of them at the end of the same function, and two slices merging meant resolving
the same three lines — for the same reason the events module did, and with the same always-correct
resolution of "take both".

**So the lines are generated from the chart, and the merge is a regeneration.** The chart already names
every slice and the fairway each belongs to, which is everything a wiring line needs. A slice that adds a
use case adds it to the chart, which it was going to do anyway, and the root is rewritten from that.

**Inside a region, not over the file.** A composition root also holds what a person wrote — the store it
opens, the middleware it installs, the order it does them in — and regenerating that would be a generator
taking over a file it does not own. So the generated lines sit between two marker comments, and everything
outside them is untouched, which is the same shape `assets/backing-services/prune.py` uses for an
alternative it may have to remove.

**Reading a region back is how the check works.** `make check-wiring` renders what the chart means and
compares it with what is between the markers. A root edited by hand inside the region is refused, with the
command that rewrites it — because a line somebody added there is a line the next regeneration silently
removes, which is the worst of both.
"""
from __future__ import annotations

import re
from pathlib import PurePosixPath

#: The marker pair. Spelled like the pruner's so a reader meeting their second region recognises it.
BEGIN = "slipwai:wiring:begin"
END = "slipwai:wiring:end"
#: How each language opens a comment, keyed by the extension of the composition root. A language absent
#: from here has no wiring generated: the rule still holds, there is simply nothing this can write.
COMMENT = {".py": "#", ".ts": "//", ".tsx": "//", ".go": "//", ".java": "//", ".kt": "//"}
#: How each language calls one slice's wiring function. The name is the slice's own, lower-cased with
#: hyphens turned into underscores, so a reader greps the slice id and finds the line.
CALL = {
    ".py": "    wire_{name}(app, store)",
    ".ts": "  wire_{name}(app, store);",
    ".tsx": "  wire_{name}(app, store);",
    ".go": "\twire_{name}(app, store)",
    ".java": "        wire_{name}(app, store);",
    ".kt": "    wire_{name}(app, store)",
}


def wiring_name(slice_id: str) -> str:
    """A slice id as an identifier: `ORD-01` becomes `ord_01`, which every language will take."""
    return re.sub(r"[^0-9a-z]+", "_", slice_id.lower()).strip("_")


def slices_of(chart: dict, fairway: str | None = None) -> list[str]:
    """The chart's slices, in its own order, which is split order — and the order they wire in.

    Split order matters here and nowhere else in this module: wiring is the one place where two slices can
    depend on each other's having run, so the generated order is the order the split agreed rather than
    whatever sorting would give.
    """
    entries = chart.get("slices")
    if not isinstance(entries, dict):
        return []
    return [str(slice_id) for slice_id, body in entries.items()
            if fairway is None or (isinstance(body, dict) and str(body.get("fairway")) == fairway)]


def region(root_path: str, chart: dict, fairway: str | None = None) -> str | None:
    """The generated block, markers included, or `None` for a language this does not write wiring for."""
    suffix = PurePosixPath(root_path).suffix
    comment, call = COMMENT.get(suffix), CALL.get(suffix)
    if not comment or not call:
        return None
    lines = [call.format(name=wiring_name(slice_id)) for slice_id in slices_of(chart, fairway)]
    body = "\n".join(lines) if lines else f"{comment} no slice wires anything yet"
    return (f"{comment} {BEGIN} — generated by `make wiring` from the chart. Never edit between the markers:\n"
            f"{comment} a line added here is one the next regeneration removes, and `make check-wiring` says so.\n"
            f"{body}\n"
            f"{comment} {END}")


def written(text: str) -> str | None:
    """What is between the markers in a root as it stands, or `None` where it has no region."""
    # Bounded at both ends by the markers' own lines. The first version ended `.*$` under DOTALL, which
    # ran to the end of the file and swallowed everything the region was supposed to leave alone.
    found = re.search(rf"^[^\n]*{re.escape(BEGIN)}.*?{re.escape(END)}[^\n]*$", text,
                      re.MULTILINE | re.DOTALL)
    return found.group(0) if found else None


def rewritten(text: str, block: str) -> str:
    """The root with its region replaced and everything outside it untouched.

    A root with no region is returned unchanged rather than having one appended: where the markers go is a
    decision about that file, and guessing it would put the wiring somewhere the store is not open yet.
    """
    current = written(text)
    return text.replace(current, block) if current else text


def drifted(text: str, block: str) -> bool:
    """Whether what is in the region differs from what the chart means."""
    current = written(text)
    return current is not None and current.strip() != block.strip()
