"""Start the interpreters the matrix needs — the plan probe and `slipwai generate` — with the package directory set.

As for the conformance suite (`slipwai.conformance.run`), the merged catalog is read at the first `import
slipwai.catalog`, from `SLIPWAI_LANGUAGES`, so the directory a maintainer names is only a process's own if it is set
before that import. Nothing here reads the catalog in the caller's process: `plan` starts `python -m
slipwai.matrix.plan` with the directory set and this keel first on the path, and reads the plan from a file, and
every project is generated by `slipwai generate` in a process of its own, the way a project maker runs it.
"""
from __future__ import annotations

import json
import tempfile
from dataclasses import dataclass, replace
from pathlib import Path

from ..conformance import child
from ..conformance.run import environment, require_package_name
from .rows import Row


@dataclass(frozen=True)
class Image:
    """One backend's image row, the tool that builds it, and the readiness path the started image must answer."""

    row: Row
    tool: str
    ready: str


@dataclass(frozen=True)
class Plan:
    """What a package's matrix runs: the backends it owns, their native-gate rows and their image rows."""

    package: str
    directory: Path
    backends: tuple[str, ...] = ()
    rows: tuple[Row, ...] = ()
    images: tuple[Image, ...] = ()

    def only(self, backends: frozenset[str] | None) -> Plan:
        """This plan restricted to `backends`, or unchanged for `None`: a slice of a run, like `FACTORY_BACKENDS`."""
        if backends is None:
            return self
        return replace(self, backends=tuple(key for key in self.backends if key in backends),
                       rows=tuple(row for row in self.rows if row.backend in backends),
                       images=tuple(image for image in self.images if image.row.backend in backends))


def row_of(said: dict) -> Row:
    return Row(said["name"], said["profile"], said["backend"], said["frontend"],
               tuple((axis, option) for axis, option in said["answers"]))


def plan(language_dir: Path | str, package: str) -> Plan:
    """The plan for `package` in `language_dir`, read in a fresh interpreter.

    A `package` that is not one directory name is a `ValueError`. A package that does not load, a catalog the rows no
    longer cover, a probe that ends without a plan, or a plan that is not the probe's shape (`validated`), is a
    `RuntimeError` saying which.
    """
    require_package_name(package)
    directory = Path(language_dir).resolve()
    with tempfile.TemporaryDirectory(prefix="slipwai-matrix-") as scratch:
        destination = Path(scratch) / "plan.json"
        done = child.run("slipwai.matrix.plan", [str(directory), package, str(destination)], environment(directory))
        try:
            said = json.loads(destination.read_text(encoding="utf-8", errors="replace"))
        except (OSError, ValueError):
            said = None
    if not isinstance(said, dict):
        raise RuntimeError(f"the matrix plan for {package} did not report (exit {done.returncode}). "
                           f"Last line: {done.last_line()}")
    if "refused" in said and set(said) == {"refused"} and lines(said["refused"]):
        raise RuntimeError(f"the matrix for {package} cannot be planned: " + "; ".join(said["refused"]))
    return validated(package, directory, said)


def lines(value: object) -> bool:
    return isinstance(value, list) and all(isinstance(line, str) for line in value)


def row_shaped(said: object) -> bool:
    """Whether `said` is a row as the probe writes it: four names and a list of `[axis, option]` pairs."""
    return (isinstance(said, dict) and set(said) == {"name", "profile", "backend", "frontend", "answers"}
            and all(isinstance(said[key], str) for key in ("name", "profile", "backend", "frontend"))
            and isinstance(said["answers"], list)
            and all(lines(pair) and len(pair) == 2 for pair in said["answers"]))


def validated(package: str, directory: Path, said: object) -> Plan:
    """The probe's report as a `Plan`, or a `RuntimeError` where it is not the shape the probe writes: the backends
    named once each, every row and image one of theirs, and each backend with rows and exactly one image — a plan
    that names a backend and runs nothing for it is never read as a pass."""
    def malformed(why: str) -> RuntimeError:
        return RuntimeError(f"the matrix plan for {package} wrote a plan that is not one: {why}")

    if not isinstance(said, dict) or set(said) != {"backends", "rows", "images"}:
        raise malformed('it is not {"backends": [...], "rows": [...], "images": [...]}')
    backends, rows, images = said["backends"], said["rows"], said["images"]
    if not lines(backends) or len(set(backends)) != len(backends):
        raise malformed("its backends are not a list of names, each once")
    if not isinstance(rows, list) or not all(row_shaped(row) for row in rows):
        raise malformed("a row is not {name, profile, backend, frontend, answers: [[axis, option], ...]}")
    if not isinstance(images, list) or not all(
            isinstance(image, dict) and set(image) == {"row", "tool", "ready"} and row_shaped(image["row"])
            and isinstance(image["tool"], str) and isinstance(image["ready"], str) for image in images):
        raise malformed("an image is not {row, tool, ready}")
    stray = sorted({row["backend"] for row in [*rows, *(image["row"] for image in images)]} - set(backends))
    if stray:
        raise malformed(f"it has rows for {', '.join(stray)}, which it does not plan")
    for backend in backends:
        if not any(row["backend"] == backend for row in rows):
            raise malformed(f"backend {backend} has no rows")
        if sum(image["row"]["backend"] == backend for image in images) != 1:
            raise malformed(f"backend {backend} has no image, or more than one")
    return Plan(package, directory, tuple(backends), tuple(row_of(row) for row in rows),
                tuple(Image(row_of(image["row"]), image["tool"], image["ready"]) for image in images))


def generate(language_dir: Path, parent: Path, row: Row) -> tuple[Path | None, str]:
    """`slipwai generate` for `row` into `parent`: the project's directory, or `None` and the last line it said."""
    done = child.run("slipwai", ["generate", row.name, *row.arguments(), "--output", str(parent), "--skip-checks"],
                     environment(language_dir))
    if done.returncode == 0:
        return parent / row.name, ""
    return None, done.last_line() or f"exit {done.returncode}"
